home/urls.py
from . import views
from django.urls import path

app_name = "app"

urlpatterns = [
    path("", views.home),
    path("dashboard", views.dashboard),
    path("customer", views.Customer, name="customer"),
    path("client", views.Client, name="client"),
    path("council", views.council, name="council"),
    path("archive", views.archive, name="archive"),
    path("finance", views.Finance, name="finance"),
    path("adminview", views.Admin, name="admin"),
    path("hr", views.HR, name="hr"),
    path("add_customer", views.add_customer, name="add_customer"),
    path("add_client", views.add_client, name="add_client"),
    path("import_customers/", views.import_customers_view, name="import_customers"),
    path(
        "bulk_remove_customers/",
        views.bulk_remove_customers,
        name="bulk_remove_customers",
    ),
    path("bulk_remove_clients/", views.bulk_remove_clients, name="bulk_remove_clients"),
    path("action_submit/<int:customer_id>/", views.action_submit, name="action_submit"),
    path(
        "close_action_submit/<int:customer_id>/",
        views.close_action_submit,
        name="close_action_submit",
    ),
    path(
        "na_action_submit/<int:customer_id>/",
        views.na_action_submit,
        name="na_action_submit",
    ),
    path(
        "lm_action_submit/<int:customer_id>/",
        views.lm_action_submit,
        name="lm_action_submit",
    ),
    path(
        "client_action_submit/<int:client_id>/",
        views.client_action_submit,
        name="client_action_submit",
    ),
    path(
        "close_client_action_submit/<int:customer_id>/",
        views.close_client_action_submit,
        name="close_client_action_submit",
    ),
    path(
        "na_client_action_submit/<int:client_id>/",
        views.na_client_action_submit,
        name="na_client_action_submit",
    ),
    path(
        "lm_client_action_submit/<int:client_id>/",
        views.lm_client_action_submit,
        name="lm_client_action_submit",
    ),
    path(
        "council_action_submit/<int:council_id>/",
        views.council_action_submit,
        name="council_action_submit",
    ),
    path(
        "na_council_action_submit/<int:council_id>/",
        views.na_council_action_submit,
        name="na_council_action_submit",
    ),
    path("edit_customer/<int:customer_id>", views.edit_customer, name="edit_customer"),
    path("edit_client/<int:client_id>", views.edit_client, name="edit_client"),
    path(
        "remove_customer/<int:customer_id>",
        views.remove_customer,
        name="remove_customer",
    ),
    path(
        "remove_client/<int:client_id>",
        views.remove_client,
        name="remove_client",
    ),
    path("edit_council/<int:council_id>", views.edit_council, name="edit_council"),
    path(
        "remove_council/<int:council_id>",
        views.remove_council,
        name="remove_council",
    ),
    path(
        "customer-detail/<int:customer_id>/<int:s_customer_id>",
        views.customer_detail,
        name="customer_detail",
    ),
    path(
        "customer-detail/<int:customer_id>",
        views.customer_detail,
        name="customer_detail",
    ),
    path(
        "client-detail/<int:client_id>",
        views.client_detail,
        name="client_detail",
    ),
    path(
        "council-detail/<int:council_id>",
        views.council_detail,
        name="council_detail",
    ),
    path("add_client", views.add_client, name="add_client"),
    path("add_local_authority", views.add_local_authority, name="add_local_authority"),
    path("add_campaign/<int:client_id>", views.add_campaign, name="add_campaign"),
    path("add_product/<int:client_id>", views.add_product, name="add_product"),
    path(
        "add_funding_route/<int:council_id>",
        views.add_funding_route,
        name="add_funding_route",
    ),
    path("edit_product/<int:product_id>", views.edit_product, name="edit_product"),
    path(
        "edit_funding_route/<int:funding_route_id>",
        views.edit_funding_route,
        name="edit_funding_route",
    ),
    path("edit_client/<int:client_id>", views.edit_client, name="edit_client"),
    path("remove_client/<int:client_id>", views.remove_client, name="remove_client"),
    path(
        "remove_campaign/<int:campaign_id>/<int:client_id>",
        views.remove_campaign,
        name="remove_campaign",
    ),
    path(
        "remove_product/<int:product_id>",
        views.remove_product,
        name="remove_product",
    ),
    path(
        "add_child_customer/<int:customer_id>",
        views.add_child_customer,
        name="add_child_customer",
    ),
    path(
        "make_primary/<int:parent_customer_id>/<int:child_customer_id>",
        views.make_primary,
        name="make_primary",
    ),
    path(
        "add_council_funding_route/<int:council_id>",
        views.add_council_funding_route,
        name="add_council_funding_route",
    ),
    path(
        "remove_funding_route/<int:route_id>",
        views.remove_funding_route,
        name="remove_funding_route",
    ),
    path("stages/<int:client_id>", views.create_stage, name="create_stage"),
    path("product", views.product, name="product"),
    path("funding_route", views.funding_route, name="funding_route"),
    path(
        "add_product_client/<int:client_id>",
        views.add_product_client,
        name="add_product_client",
    ),
    path(
        "add_route_client/<int:client_id>",
        views.add_route_client,
        name="add_route_client",
    ),
    path("remove_stage/<int:stage_id>", views.remove_stage, name="remove_stage"),
    path("edit_stage/<int:stage_id>", views.edit_stage, name="edit_stage"),
    path(
        "set_customer_route/<int:customer_id>/<int:route_id>",
        views.set_customer_route,
        name="set_customer",
    ),
    path(
        "set_stage_values/<int:customer_id>",
        views.set_stage_values,
        name="set_stage_values",
    ),
    path(
        "remove_customer_route/<int:customer_id>",
        views.remove_customer_route,
        name="remove_customer_route",
    ),
    path("assign_agents", views.assign_agents, name="assign_agents"),
    path("assign_agent", views.assign_agent, name="assign_agent"),
    path("send_email/<int:customer_id>", views.send_email, name="send_email"),
    path(
        "send_client_email/<int:customer_id>",
        views.send_client_email,
        name="send_client_email",
    ),
    path("query/cities/<str:q>", views.query_city, name="query_city"),
    path("query/countys/<str:q>", views.query_county, name="query_county"),
    path("query/countries/<str:q>", views.query_country, name="query_country"),
    path("add_template", views.add_template, name="add_template"),
    path("edit_template/<int:template_id>", views.edit_template, name="edit_template"),
    path(
        "remove_template/<int:template_id>",
        views.remove_template,
        name="remove_template",
    ),
    path("add_reason", views.add_reason, name="add_reason"),
    path("edit_reason/<int:reason_id>", views.edit_reason, name="edit_reason"),
    path("remove_reason/<int:reason_id>", views.remove_reason, name="remove_reason"),
    path("add_signature", views.add_signature, name="add_signature"),
    path(
        "edit_signature/<int:signature_id>", views.edit_signature, name="edit_signature"
    ),
    path(
        "remove_signature/<int:signature_id>",
        views.remove_signature,
        name="remove_signature",
    ),
    path("get_notifications", views.get_notifications, name="get_notifications"),
    path(
        "add_coverage_areas/<int:client_id>",
        views.add_coverage_areas,
        name="add_coverage_areas",
    ),
    path(
        "archive_campaign/<int:client_id>/<int:campaign_id>",
        views.archive_campaign,
        name="archive_campaign",
    ),
    path(
        "archive_product/<int:client_id>/<int:product_id>",
        views.archive_product,
        name="archive_product",
    ),
    path(
        "archive_route/<int:client_id>/<int:route_id>",
        views.archive_route,
        name="archive_route",
    ),
    path(
        "get_campaign/<int:client_id>",
        views.get_campaign,
        name="get_campaign",
    ),
    path(
        "change_customer_client/<int:customer_id>",
        views.change_customer_client,
        name="change_customer_client",
    ),
    path("stage_template", views.stage_template, name="stage_template"),
    path(
        "edit_local_funding_route/<int:funding_route_id>",
        views.edit_local_funding_route,
        name="edit_local_funding_route",
    ),
    path(
        "add_new_funding_route",
        views.add_new_funding_route,
        name="add_new_funding_route",
    ),
    path(
        "make_template_stage/<int:stage_id>",
        views.make_template_stage,
        name="make_template_stage",
    ),
    path(
        "edit_new_funding_route/<int:route_id>",
        views.edit_new_funding_route,
        name="edit_new_funding_route",
    ),
    path("remove_doc/<int:doc_id>", views.remove_doc, name="remove_doc"),
    path("questions", views.questions, name="questions"),
    path("add_question", views.add_question, name="add_question"),
    path("add_action", views.add_action, name="add_action"),
    path("edit_question/<int:question_id>", views.edit_question, name="edit_question"),
    path("edit_action/<int:action_id>", views.edit_action, name="edit_action"),
    path(
        "delete_question/<int:question_id>",
        views.delete_question,
        name="delete_question",
    ),
    path("delete_action/<int:action_id>", views.delete_action, name="delete_action"),
    path("add_new_product", views.add_new_product, name="add_new_product"),
    path(
        "edit_new_product/<int:product_id>",
        views.edit_new_product,
        name="edit_new_product",
    ),
    path(
        "delete_product/<int:product_id>", views.delete_product, name="delete_product"
    ),

reform_crm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls'),name='user')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home/add_new_product.html
{% extends "base.html" %} {% load static %}  {% block css %}

  <style>

    svg{
      cursor: pointer;
    }
.container{
    text-align: center;
    margin: auto;
    background-color: white;
    border-radius: 16px;
    box-shadow: rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;
}

.header-section{
    padding: 25px 0px;
}
.header-section h1{
    font-weight: 500;
    font-size: 1.7rem;
    text-transform: uppercase;
    color: #707EA0;
    margin: 0px;
    margin-bottom: 8px;
}
.header-section p{
    margin: 5px;
    font-size: 0.95rem;
    color: #707EA0;
}

.drop-section{
    border: 1px dashed #A8B3E3;
    background-image: linear-gradient(180deg, white, #F1F6FF);
    margin: 5px 35px 35px 35px;
    border-radius: 12px;
    position: relative;
}
.drop-section div.col:first-child{
    opacity: 1;
    visibility: visible;
    transition-duration: 0.2s;
    transform: scale(1);
    margin: auto;
}
.drop-section div.col:last-child{
    font-size: 40px;
    font-weight: 700;
    color: #c0cae1;
    position: absolute;
    top: 0px;
    bottom: 0px;
    left: 0px;
    right: 0px;
    margin: auto;
    pointer-events: none;
    opacity: 0;
    visibility: hidden;
    transform: scale(0.6);
    transition-duration: 0.2s;
}
/* we will use "drag-over-effect" class in js */
.drag-over-effect div.col:first-child{
    opacity: 0;
    visibility: hidden;
    pointer-events: none;
    transform: scale(1.1);
}
.drag-over-effect div.col:last-child{
    opacity: 1;
    visibility: visible;
    transform: scale(1);
}
.drop-section span,
.drop-section button{
    display: block;
    margin: auto;
    color: #707EA0;
    margin-bottom: 10px;
}
.drop-section button{
    color: white;
    background-color: #5874C6;
    border: none;
    outline: none;
    padding: 7px 20px;
    border-radius: 8px;
    margin-top: 20px;
    cursor: pointer;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px;
}
.drop-section input{
    display: none;
}

.list-section{
    display: none;
    text-align: left;
    padding-bottom: 20px;
}
.list-section .list-title{
    font-size: 0.95rem;
    color: #707EA0;
}
.list-section li{
    display: flex;
    padding-top: 4px;
    padding-bottom: 2px;
    border-radius: 8px;
    transition-duration: 0.2s;
}
.list-section li:hover{
    box-shadow: #E3EAF9 0px 0px 4px 0px, #E3EAF9 0px 12px 16px 0px;
}
.list-section li .col{
    flex: .1;
}
.list-section li .col:nth-child(1){
    flex: .15;
    text-align: center;
}
.list-section li .col:nth-child(2){
    flex: .75;
    text-align: left;
    font-size: 0.9rem;
    color: #3e4046;
    padding: 8px 10px;
}
.list-section li .col:nth-child(2) div.name{
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    display: inline-block;
}
.list-section li .col .file-name span{
    color: #707EA0;
    float: right;
}
.list-section li .file-progress{
    height: 5px;
    margin-top: 8px;
    border-radius: 8px;
    background-color: #dee6fd;
}
.list-section li .file-progress span{
    display: block;
    border-radius: 8px;
    background-image: linear-gradient(120deg, #6b99fd, #9385ff);
    transition-duration: 0.4s;
}
.list-section li .col .file-size{
    font-size: 0.75rem;
    margin-top: 3px;
    color: #707EA0;
}
.list-section li .col svg.cross,
.list-section li .col svg.tick{
    fill: #8694d2;
    background-color: #dee6fd;
    position: relative;
    transform: translate(-50%, -50%);
    border-radius: 50%;
}
.list-section li .col svg.tick{
    fill: #50a156;
    background-color: transparent;
}
.list-section li.complete span,
.list-section li.complete .file-progress,
.list-section li.complete svg.cross{
    display: none;
}
.list-section li.in-prog .file-size,
.list-section li.in-prog svg.tick{
    display: none;
}

  </style>

{% endblock %} {%block content%}

<div class="container-fluid" style="max-width: 1500px">
  <div class="row">
    <div class="col-lg-12 d-flex align-items-strech w-100">
      <div class="card w-100">
        <div class="card-body">
          <div
            class="d-sm-flex d-block align-items-center justify-content-between mb-9"
          >
            <div class="mb-3 mb-sm-0">
              <a href="{% url 'app:add_new_product' %}">
                <h5
                  class="card-title fw-semibold text-primary text-decoration-underline"
                >
                  Add Product
                </h5></a
              >
            </div>
          </div>
          <div>
            <form
              name="addClientForm"
              id="addClientForm"
              method="post"
              action="{% url 'app:add_new_product' %} "
              enctype="multipart/form-data"
            >
              {% csrf_token %}

              <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input
                  type="text"
                  class="form-control"
                  id="name"
                  name="name"
                  required
                />
              </div>

              <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <input
                  type="text"
                  class="form-control"
                  id="description"
                  name="description"
                  required
                />
              </div>

              <div class="mb-3">
                <label for="formFile" class="form-label">Documentation</label>
                <div class="container">
                  <div class="drop-section">
                      <div class="col">
                          <button type="button" class="file-selector">Browse Files</button>
                          <input type="file" id="formFile" name="document" accept="application/pdf" class="from-input file-selector-input" multiple>
                      </div>
                      <div class="col">
                          <div class="drop-here">Drop Here</div>
                      </div>
                  </div>
                  <div class="list-section">
                      <div class="list-title">Uploaded Files</div>
                      <div class="list"></div>
                  </div>
              </div>

              <button id="submitBtn" type="button" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% comment %} <script>
  submitBtn = document.getElementById("submitBtn");
  submitBtn.addEventListener("click", function () {
    submitBtn.disabled = true;
    submitBtn.innerHTML = "Loading...";
    document.getElementById("addClientForm").submit();
  });
</script> {% endcomment %}

<script >
  const dropArea = document.querySelector(".drop-section");
const listSection = document.querySelector(".list-section");
const listContainer = document.querySelector(".list");
const fileSelector = document.querySelector(".file-selector");
const fileSelectorInput = document.querySelector(".file-selector-input");

// upload files with browse button
fileSelector.onclick = () => fileSelectorInput.click();
fileSelectorInput.onchange = () => {
  [...fileSelectorInput.files].forEach((file) => {
    if (typeValidation(file.type)) {
      uploadFile(file);
    }
  });
};

// check the file type
function typeValidation(type) {
  var splitType = type.split("/")[0];
  if (type == "application/pdf") {
    return true;
  }
}

// when file is over the drag area
dropArea.ondragover = (e) => {
  e.preventDefault();
  [...e.dataTransfer.items].forEach((item) => {
    if (typeValidation(item.type)) {
      dropArea.classList.add("drag-over-effect");
    }
  });
};
// when file leave the drag area
dropArea.ondragleave = () => {
  dropArea.classList.remove("drag-over-effect");
};
// when file drop on the drag area
dropArea.ondrop = (e) => {
  e.preventDefault();
  dropArea.classList.remove("drag-over-effect");
  if (e.dataTransfer.items) {
    [...e.dataTransfer.items].forEach((item) => {
      if (item.kind === "file") {
        const file = item.getAsFile();
        if (typeValidation(file.type)) {
          uploadFile(file);
        }
      }
    });
  } else {
    [...e.dataTransfer.files].forEach((file) => {
      if (typeValidation(file.type)) {
        uploadFile(file);
      }
    });
  }
};

// Array to store uploaded files
let queuedFiles = [];

// Upload file function
function uploadFile(file) {
  listSection.style.display = "block";
  var li = document.createElement("li");
  li.classList.add("in-prog");
  li.innerHTML = `
        <div class="col">
            <img src="icons/${iconSelector(file.type)}" alt="">
        </div>
        <div class="col">
            <div class="file-name">
                <div class="name">${file.name}</div>
                <span></span>
            </div>
            <div class="file-size">${(file.size / (1024 * 1024)).toFixed(
              2
            )} MB</div>
        </div>
        <div class="col">
            <svg xmlns="http://www.w3.org/2000/svg" class="cross" height="20" width="20"><path d="m5.979 14.917-.854-.896 4-4.021-4-4.062.854-.896 4.042 4.062 4-4.062.854.896-4 4.062 4 4.021-.854.896-4-4.063Z"/></svg>
            <svg xmlns="http://www.w3.org/2000/svg" class="tick" height="20" width="20"><path d="m8.229 14.438-3.896-3.917 1.438-1.438 2.458 2.459 6-6L15.667 7Z"/></svg>
        </div>
    `;
  listContainer.prepend(li);

  // Create FormData object and append necessary fields
  var data = new FormData();
  data.append("documents", file);
  // Add file to queued files
  queuedFiles.push({ file: file, formData: data, listItem: li });

  // Set up remove handler
  li.querySelector(".cross").onclick = () => {
    // Remove file from queuedFiles array
    const index = queuedFiles.findIndex((item) => item.file === file);
    if (index !== -1) {
      queuedFiles.splice(index, 1);
    }
    // Remove the list item from the DOM
    li.remove();
  };
  console.log(queuedFiles);
}

// Submit button click handler
document.querySelector("#submitBtn").addEventListener("click", (event) => {
  document.querySelector("#submitBtn").innerHTML = "Loading...";
  document.querySelector("#submitBtn").disabled = true;
  const checkboxinputs = document.querySelectorAll(".checkboxinput");
    if (checkboxinputs){
      checkboxinputs.forEach((checkboxinput) => {
        const checkboxdiv = checkboxinput.parentElement;
        const radios = checkboxdiv.querySelectorAll("input[type='radio']");
        radios.forEach((radio) => {
          if (radio.checked) {
            checkboxdiv.querySelector("input[name='dynamicRule']").value = `${checkboxinput.value},${radio.value}`;
          }
        });
      });
    }
    event.preventDefault(); // Prevent default form submission
    const options = document.querySelectorAll('.option');
    options.forEach(option => {
        option.parentElement.parentElement.children[0].value = option.parentElement.parentElement.children[0].value + ',' + option.parentElement.children[0].value;
    });

    var name = document.querySelector("#name").value;
    var description = document.querySelector("#description").value;
        
    

    var allData = new FormData();
    allData.append("name", name);
    allData.append("description", description);
    
    queuedFiles.forEach((queuedFile) => {
        allData.append("document", queuedFile.file);
    });

    var http = new XMLHttpRequest();
    http.onload = () => {
        console.log("Files uploaded successfully");
        queuedFiles = [];
        document.querySelector(".list").innerHTML = "";
        window.location.href=`/product`;
    };
    const csrftoken = document.querySelector("[name=csrfmiddlewaretoken]").value;

    http.open("POST", `/add_new_product`, true);
    http.setRequestHeader("X-CSRFToken", csrftoken);
    http.send(allData);
});


// Helper function to get CSRF token from cookie
function getCookie(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== "") {
    var cookies = document.cookie.split(";");
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === name + "=") {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}

// find icon for file
function iconSelector(type) {
  var splitType =
    type.split("/")[0] == "application"
      ? type.split("/")[1]
      : type.split("/")[0];
  return splitType + ".png";
}

</script>

{% endblock content %}

templates/home/add_stage.html
{% extends "base.html" %} {% load static %} {%block content%}

<div class="container-fluid" style="max-width: 1500px">
  <div class="row">
    <div class="col-lg-12 d-flex align-items-strech w-100">
      <div class="card w-100">
        <div class="card-body">
          <div
            class="d-sm-flex d-block align-items-center justify-content-between mb-9"
          >
            <div class="mb-3 mb-sm-0">
              <a href="{% url 'app:add_stage' %}">
                <h5
                  class="card-title fw-semibold text-primary text-decoration-underline"
                >
                  Add Stage
                </h5></a
              >
            </div>
          </div>
          <div>
            <form
              name="addClientForm"
              id="addClientForm"
              method="post"
              action="{% url 'app:add_stage' %} "
            >
              {% csrf_token %}

              <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input
                  type="text"
                  class="form-control"
                  id="name"
                  name="name"
                  required
                />
              </div>

              <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <input
                  type="text"
                  class="form-control"
                  id="description"
                  name="description"
                  required
                />
              </div>

              <button id="submitBtn" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  submitBtn = document.getElementById("submitBtn");
  submitBtn.addEventListener("click", function () {
    submitBtn.disabled = true;
    submitBtn.innerHTML = "Loading...";
    document.getElementById("addClientForm").submit();
  });
</script>

{% endblock content %}

templates/home/cj_product.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="row container-fluid">
  {% for message in messages %}
  <div
    class="alert {{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %}

  <div class="container-fluid pt-4">
    <div class="card p-0">
      <div class="card-body p-3 m-0">
        <h5 class="card-title">Customer Journey - {{ route.name }} - {{ product.name }}</h5>
        <div
          class="d-sm-flex d-block align-items-center justify-content-between mb-9"
        >
          <div class="mb-3 mb-sm-0">
            <a href="{% url 'app:funding_route' %}">
              <h5
                class="card-title fw-semibold text-primary text-decoration-underline"
              >
                Customer Journey Management
              </h5></a
            >
          </div>
          <div>
            
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addStage">
              Add Stage
            </button>

            <div class="modal fade" id="addStage" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <form action="{% url 'app:cj_product' route.id product.id %}" method="post">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Stage</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    {% csrf_token %}
                    <select class="form-select" name="stage" aria-label="Default select example">
                      {% for stage in stages %}
                        <option value="{{stage.id}}">{{stage.name}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button class="btn btn-primary">Submit</button>
                  </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div style="overflow-x: auto">
          <table class="table" style="overflow-x: auto">
            <thead>
              <tr>
                <th>Stage</th>
              </tr>
            </thead>
            <tbody>
              {% if product.stage.all %} {% for stage in product.stage.all %}
              <tr>
                <td>
                  <a href="{% url 'app:cj_stage' route.id product.id stage.id %}">
                  {{ stage.name }} </a>
                </td>
                <td><a href="/delete_cj_stage/{{ route.id }}/{{ product.id }}/{{stage.id}}">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="text-danger icon icon-tabler icon-tabler-trash"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M4 7l16 0" />
                    <path d="M10 11l0 6" />
                    <path d="M14 11l0 6" />
                    <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                    <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                  </svg>
                </a></td>
              </tr>
              {% endfor %} {% else %}
              <tr
                class="text-center display-flex align-items-center justify-content-center"
              >
                <td colspan="9" class="text-center">No Stages</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/home/finance.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
  <!--  Row 1 -->
  <div class="row">
    <div class="col-lg-12 d-flex align-items-strech">
      <div class="card w-100">
        <div class="card-body">
          <div class="d-sm-flex d-block align-items-center justify-content-between mb-9">
            <div class="mb-3 mb-sm-0">
              <h5 class="card-title fw-semibold">Sample Card</h5>
            </div>
            {% comment %} <div>
              <select class="form-select">
                <option value="1">March 2023</option>
                <option value="2">April 2023</option>
                <option value="3">May 2023</option>
                <option value="4">June 2023</option>
              </select>
            </div> {% endcomment %}
          </div>
          <div>
            <h1>
              Welcome to Finance Page
            </h1>
          </div>
        </div>
      </div>
    </div>
    

  {% endblock content %}

templates/home/hr.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
  <!--  Row 1 -->
  <div class="row">
    <div class="col-lg-12 d-flex align-items-strech">
      <div class="card w-100">
        <div class="card-body">
          <div class="d-sm-flex d-block align-items-center justify-content-between mb-9">
            <div class="mb-3 mb-sm-0">
              <h5 class="card-title fw-semibold">Sample Card</h5>
            </div>
            {% comment %} <div>
              <select class="form-select">
                <option value="1">March 2023</option>
                <option value="2">April 2023</option>
                <option value="3">May 2023</option>
                <option value="4">June 2023</option>
              </select>
            </div> {% endcomment %}
          </div>
          <div>
            <h1>
              Welcome to HR Page
            </h1>
          </div>
        </div>
      </div>
    </div>
    

  {% endblock content %}